### ISSUE TITLE
"Undefined array key DB_DATABASE" Error when commenting on PR without DB configured

### ISSUE THREAD

**Issue by gbradley** [mehrancodes/laravel-harbor#56]
In playing around with Veyoze I've come across this error when `GIT_COMMENT_ENABLED` is true but no env variables have been explicitly set (although Forge seems to default to the server's existing DB name when generating the initial .env).

![Screenshot 2024-02-08 at 19 17 40](https://github.com/mehrancodes/veyoze/assets/116627/b32509f3-57b3-42d9-84e6-9c52e636499b)

Obviously most will be passing in explicit DB vars but thought I'd let you know. Other than this its working well so far!

**Comment by mehrancodes** [comment]
Looks like enabling the PR comments requires **FORGE_DB_CREATION_REQUIRED** to be true. I'll consider this fix for next release soon.

**Comment by mehrancodes** [comment]
@gbradley The issue just fixed, of course with some enhancements to make sure we don't have break when enabling PR comments.

FYI the package name has just been changed to laravel-harbor :) Make sure to update your workflows 🚀
