### ISSUE TITLE
Comment not including the correct environment URL

### ISSUE THREAD

**Issue by gbradley** [mehrancodes/laravel-harbor#72]
A recent site resulted in the following GitHub comment being created:

![Screenshot 2024-02-27 at 17 45 48](https://github.com/mehrancodes/laravel-harbor/assets/116627/9912aa1e-be7a-4333-a68e-1adfcf689062)

It appears the "Environment Url" `$name` property from the EnvironmentUrlBuilder is being passed in ratehr than the actual url? I haven't had time to dig into the code yet but will submit a PR if I can identify the problem.

**Comment by mehrancodes** [comment]
This is interesting. The environment url's value comes from the (Forge site name)[https://forge.laravel.com/api-documentation#get-site] which is expected to be a domain name.

By any chance, does it still happening for you? As it works correctly for me already.

**Comment by mehrancodes** [comment]
Today I noticed an inconsistency with the database URL name on the PR comment. Currently, it's set as "DatabaseBuilder Url" instead of "Database Url," which is incorrect. 

<img width="863" alt="Screenshot 2024-03-05 at 18 21 20" src="https://github.com/mehrancodes/laravel-harbor/assets/7046255/586fff79-3ee2-441f-ad48-f9abc7cfdb13">

**Comment by mehrancodes** [comment]
Fixed the **DatabaseBuilder Url** name.

I'm closing this issue since the Environment Url looks right. Feel free to comment or open a new issue if it's still wrong.

**Comment by gbradley** [comment]
Hi, yes I’ve never had this happen again, very odd. The only issue I’ve noticed is the URL seems to use http:// even when SSL has been enabled, but I haven’t checked that recently so may open a separate issue.
