### ISSUE TITLE
Forge deployment timing out

### ISSUE THREAD

**Issue by shawnhooper** [mehrancodes/laravel-harbor#74]
My deployment times out while `npm run production` is running. The site works once the script finishes running, but the Github Action for Harbor has failed at this point, so doesn't get to the step of commenting in the Git repo.

Would it be possible to flag a project as having a long deployment:

1. Extend the timeout if whatever is timing out is on the Harbor side of the connection. 
or 
2. Have a flag that a long deployment is expected, and then catch the timeout exception, and assume that it will complete correctly.  Continue on to Git commenting anyway.

**Comment by mehrancodes** [comment]
👋 Hi Shawn,

By any chance have you tried the [FORGE_TIMEOUT_SECONDS](https://laravel-harbor.com/docs/configuration/#forge-timeout-seconds)?

**Comment by shawnhooper** [comment]
Hi Mehran 👋 

That did the trick!  #facepalm 

Thank you.

**Comment by mehrancodes** [comment]
Yeah, many thanks to @mgkimsal for introducing this feature! 👨🏻‍💻🚀🙂
