### ISSUE TITLE
Slack Integration

### ISSUE THREAD

**Issue by shawnhooper** [mehrancodes/laravel-harbor#77]
@mehrancodes I know that Slack integration is on your roadmap.  Is this something you're already working on?  If not, mind if I take it on?

I just didn't want to start if you had it in progress.

**Comment by mehrancodes** [comment]
Yes, I haven't had a chance to start it yet, and I would really appreciate your suggestion. Let's do it 🤩

If you've got a question, I'd be glad to help.
